version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/api-client/node_modules
      - /app/packages/utils/node_modules
      - /app/packages/ui-kit/node_modules
      - /app/apps/main-app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001 