version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    command: pnpm dev
    volumes:
      - .:/app
      - /app/apps/main-app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - TURBO_FORCE=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app/apps/main-app 